let head = document.getElementById("heading")
console.log(head.innerText)

let paragraph =document.getElementsByClassName("text")
console.log(paragraph[0].innerText)

let allparagraphs = document.getElementsByTagName("p")
console.log(allparagraphs.length)

let firstpara = document.querySelector(".text")
console.log(firstpara.innerHTML)

let selectAll = document.querySelectorAll(".text")
selectAll.forEach( console.log()
)
console.log(selectAll)

let heading = document.getElementById(heading)
heading.style.color = "red"
heading.style.fontSize = "20px"
heading.style.backgroundColor = "black"
//selectAll.fper



