let a = "mememe"
console.log(a.toUpperCase());

let b = "meMEme"
console.log(b.toUpperCase());

let word = "i don't" // 7 characters
console.log(word.length);

let c = "emeka eze"
console.log(c.charAt(0));

let d = "how many characters are in this string"
console.log(d.replace("string", "number"));
console.log(d.replace("string", "100"));

let e = "sanni i enjoyed sunday prayer service ! i love to play and play video game how many characters is in this number"
e = e.replace("sanni", "emeka and")
e = e.replace("play video game", "play basketball")
console.log(e);






