// TASK 1
let userName = "Lagos" // string
let age = 25 // number
let isHappy = false // boolean  
let noValue = null // null
let notAssigned // undefined
let favoriteColors = ["red", "blue", "yellow"] // array 
let user = { city: "Lagos", country: "Nigeria" } // object

//TASK 2
let Name = "Emeka" 
console.log(Name);

let myage = 18  
console.log(myage);

let student = false
console.log(student);
   
let a = null 
console.log(a);

let B;  
console.log(B);

let favoritefoods = ["rice", "yam", "potato"]
console.log(favoritefoods);
 
let Favorite = { book: "re:zero", author: "tappei nagatsuki" } 
console.log(Favorite);

//TASK 3
console.log(typeof Name);
console.log(typeof myage);
console.log(typeof student);
console.log(typeof a);
console.log(typeof B);
console.log(typeof favoritefoods);
console.log(typeof Favorite);

//TASK 4
let c = "eze"
c = 20
console.log(c);


let place = ["nigeria",  "japan", "america"]
place = { planet: "earth", star: "sun"}
console.log(place);


let t = false
t = null
console.log(t);


//TASK 5
let f = 1
let r = 10
console.log(f * r);

let z = "My name is"
let i = "Emeka Eze"
console.log(z +  i);

let we = 3
let us = "3"
console.log(we + us); // result is 33, because the value for us is a sring, the two values were put together rather than calculated

let plate = ["glass",  "plastic", "metal"]
console.log(plate);

let p = { space: "moon", sky: "blue"}
console.log(p);

//TASK 6
let newBasket = "fruits" // string, the semi column was removed
let undefinedVar; //undefined  
console.log(undefinedVar);//the u  was changed from capital to small letter
console.log(typeof newBasket);  //the n was changed from capital to small letter
newBasket = 45; 
console.log(typeof newBasket);










