
//TASK 1
let country = "Nigeria" // string
let population = 200000000 // number
let isDeveloped = false // boolean
let currentPresident = null; // null
let futureGoal; // undefined
let landmarks = ["Obudu", "Zuma Rock", "Lekki Bridge"] // array 
let stateInfo = { name: "Lagos", population: 21000000 } // object

//TASK 2
let movie = "sonic"
let randomage = 60
let tea = false
let brave = null;
let hobbies = ["reading", "gaming"]
let car = {brand: "tesla", model: "3rd", year: "2016"}

//TASK 3
let a = "my"
let b = "dog"
console.log(a + b);

let c = 1
let d = 2
console.log(c + d);
console.log(c * d);
console.log(d - c);
console.log(d / c);

//TASK 4
let firstName = "Michael"// michael was quoted 
console.log(typeof firstName)// f was changed from capital letter to small letter
let address = { city: "Lagos", country: "Nigeria" }// nigeria was quoted  
console.log(typeof address);




