//if (condition)
let even_number = [20];
let odd_numbers = []
if (11 == even_number){
    console.log(even_number);
}else{
    console.log(odd_numbers);
    
}

let age = 18
if (age >= 18){
    console.log("you are old enough to drive");
}else{
    console.log("you are not old enough to drive");
    
}
    
let score = "30"

if (score >= 90){
    console.log("grade: A");
}else if(score >= 80){
    console.log("Grade: B");
}else if(score >= 70){
    console.log("Grade: c");
}else{
    console.log("FAILED");
    
}


